version: '2'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: webscrapbook_test
    ports:
      - 8080:8080
    volumes:
        - ./:/data
    command: build
    