#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"
echo "[***] - Version $SOURCE_BRANCH"


if [ "$SOURCE_BRANCH" == "master" ]; then
    docker build \
		-t $IMAGE_NAME .
elif [ "$SOURCE_BRANCH" == "dev" ]; then
	docker build \
		-t $IMAGE_NAME .
else
	docker build \
		--build-arg wsb_ver=$SOURCE_BRANCH \
		-t $IMAGE_NAME .
fi
